/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.parkerm;

import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.assertj.core.api.Assertions.assertThat;

class GeneratePojoJsonSchemaPluginFunctionalTest {

    private static final String testProjectDir = "build/functionalTest";
    private static File projectDir;

    @BeforeAll
    static void setUp() {
        projectDir = new File(testProjectDir);
    }

    @Test
    void canRunTask() throws IOException {
        // Setup the test build
        Files.createDirectories(projectDir.toPath());
        writeString(new File(projectDir, "settings.gradle"), "");
        writeString(new File(projectDir, "build.gradle"), "" +
                "plugins {" +
                "  id('io.github.parkerm.generate-pojo-json-schema')" +
                "}");

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("generateJsonSchema");
        runner.withProjectDir(projectDir);
        BuildResult result = runner.build();

        // Verify the result
        assertThat(result.getOutput()).contains("1 actionable task: 1 executed");
    }

    @Test
    void acceptsClassesInput() throws IOException {
        String buildScript = "" +
                "plugins {\n" +
                "  id('io.github.parkerm.generate-pojo-json-schema')\n" +
                "}\n" +
                "generateJsonSchema {\n" +
                "  classes = [Integer.class, String.class]\n" +
                "  prettyPrint = false\n" +
                "}";
        Files.createDirectories(projectDir.toPath());
        writeString(new File(projectDir, "settings.gradle"), "");
        writeString(new File(projectDir, "build.gradle"), buildScript);

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("generateJsonSchema");
        runner.withProjectDir(projectDir);

        BuildResult result = runner.build();

        Path path = projectDir.toPath().resolve(Paths.get("build", "schema", "json"));
        assertThat(path.toFile())
                .exists()
                .isDirectoryContaining(file -> file.getName().equals("String.schema.json"))
                .isDirectoryContaining(file -> file.getName().equals("Integer.schema.json"));

        String expectedIntegerSchema = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"Integer\",\"type\":\"integer\"}";
        String expectedStringSchema = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"String\",\"type\":\"string\"}";
        assertThat(path.resolve("Integer.schema.json").toFile())
                .isFile()
                .hasContent(expectedIntegerSchema);
        assertThat(path.resolve("String.schema.json").toFile())
                .isFile()
                .hasContent(expectedStringSchema);
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
