/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.parkerm;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class GeneratePojoJsonSchemaPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("generateJsonSchema", task -> {
            task.doLast(s -> System.out.println("Hello from plugin 'io.github.parkerm.generate-pojo-json-schema'"));
        });
    }
}
