/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.parkerm;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class GeneratePojoJsonSchemaPlugin implements Plugin<Project> {

    public void apply(Project project) {
        project.getTasks()
                .register("generateJsonSchema", GeneratePojoJsonSchemaTask.class);
    }
}
